development:
  adapter: postgresql
  encoding: utf8
  database: wodlandia_development
  pool: 5
  username: vagrant
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: wodlandia_test
  pool: 5
  username: vagrant
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: wodlandia_production
  pool: 5
  username: vagrant
  password:
