development:
  adapter: postgresql
  database: wodlandia_development
  username: 
  password: 
  pool: 5
  encoding: UTF8

test:
  adapter: postgresql
  database: wodlandia_test
  username: 
  password: 
  pool: 5
  encoding: UTF8

production:
  adapter: postgresql
  database: wodlandia_production
  username: 
  password: 
  pool: 5
  encoding: UTF8
