development:
  adapter: postgresql
  encoding: unicode
  database: wodlandia_development
  pool: 5
  username: janet
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wodlandia_test
  pool: 5
  username: janet
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: wodlandia_production
  pool: 5
  username: janet
  password:
